export const dummyBoardList = [
  {
    "postId": 1,
    "nickName": "작성자1",
    "title": "게시글 제목 예시 1",
    "content": "게시글 내용 예시입니다. 1",
    "createdAt": "2025.02.02T00:00:00.000000",
    "postType": "자유",
    "recommendCnt": 1,
    "viewCnt": 3,
    "uriTitle": "네이버",
    "urlPath": "https://www.naver.com/",
    "tags": "",
    "imageUrls": [],
    "recommended": false
  },
  {
    "postId": 2,
    "nickName": "작성자2",
    "title": "게시글 제목 예시 2",
    "content": "게시글 내용 예시입니다. 2",
    "createdAt": "2025.02.03T00:00:00.000000",
    "postType": "인사",
    "recommendCnt": 2,
    "viewCnt": 6,
    "uriTitle": "구글",
    "urlPath": "https://www.google.com/",
    "tags": "",
    "imageUrls": [],
    "recommended": false
  },
  {
    "postId": 3,
    "nickName": "작성자3",
    "title": "게시글 제목 예시 3",
    "content": "게시글 내용 예시입니다. 3",
    "createdAt": "2025.02.04T00:00:00.000000",
    "postType": "질문",
    "recommendCnt": 3,
    "viewCnt": 9,
    "uriTitle": "네이버",
    "urlPath": "https://www.naver.com/",
    "tags": "",
    "imageUrls": [],
    "recommended": false
  },
  {
    "postId": 4,
    "nickName": "작성자4",
    "title": "게시글 제목 예시 4",
    "content": "게시글 내용 예시입니다. 4",
    "createdAt": "2025.02.05T00:00:00.000000",
    "postType": "자유",
    "recommendCnt": 4,
    "viewCnt": 12,
    "uriTitle": "구글",
    "urlPath": "https://www.google.com/",
    "tags": "",
    "imageUrls": [],
    "recommended": false
  },
  {
    "postId": 5,
    "nickName": "작성자5",
    "title": "게시글 제목 예시 5",
    "content": "게시글 내용 예시입니다. 5",
    "createdAt": "2025.02.06T00:00:00.000000",
    "postType": "인사",
    "recommendCnt": 5,
    "viewCnt": 15,
    "uriTitle": "네이버",
    "urlPath": "https://www.naver.com/",
    "tags": "",
    "imageUrls": [],
    "recommended": false
  },
  {
    "postId": 6,
    "nickName": "작성자6",
    "title": "게시글 제목 예시 6",
    "content": "게시글 내용 예시입니다. 6",
    "createdAt": "2025.02.07T00:00:00.000000",
    "postType": "질문",
    "recommendCnt": 6,
    "viewCnt": 18,
    "uriTitle": "구글",
    "urlPath": "https://www.google.com/",
    "tags": "",
    "imageUrls": [],
    "recommended": false
  },
  {
    "postId": 7,
    "nickName": "작성자7",
    "title": "게시글 제목 예시 7",
    "content": "게시글 내용 예시입니다. 7",
    "createdAt": "2025.02.08T00:00:00.000000",
    "postType": "자유",
    "recommendCnt": 7,
    "viewCnt": 21,
    "uriTitle": "네이버",
    "urlPath": "https://www.naver.com/",
    "tags": "",
    "imageUrls": [],
    "recommended": false
  },
  {
    "postId": 8,
    "nickName": "작성자8",
    "title": "게시글 제목 예시 8",
    "content": "게시글 내용 예시입니다. 8",
    "createdAt": "2025.02.09T00:00:00.000000",
    "postType": "인사",
    "recommendCnt": 8,
    "viewCnt": 24,
    "uriTitle": "구글",
    "urlPath": "https://www.google.com/",
    "tags": "",
    "imageUrls": [],
    "recommended": false
  },
  {
    "postId": 9,
    "nickName": "작성자9",
    "title": "게시글 제목 예시 9",
    "content": "게시글 내용 예시입니다. 9",
    "createdAt": "2025.02.10T00:00:00.000000",
    "postType": "질문",
    "recommendCnt": 9,
    "viewCnt": 27,
    "uriTitle": "네이버",
    "urlPath": "https://www.naver.com/",
    "tags": "",
    "imageUrls": [],
    "recommended": false
  },
  {
    "postId": 10,
    "nickName": "작성자10",
    "title": "게시글 제목 예시 10",
    "content": "게시글 내용 예시입니다. 10",
    "createdAt": "2025.02.11T00:00:00.000000",
    "postType": "자유",
    "recommendCnt": 0,
    "viewCnt": 30,
    "uriTitle": "구글",
    "urlPath": "https://www.google.com/",
    "tags": "",
    "imageUrls": [],
    "recommended": false
  },
  {
    "postId": 11,
    "nickName": "작성자11",
    "title": "게시글 제목 예시 11",
    "content": "게시글 내용 예시입니다. 11",
    "createdAt": "2025.02.12T00:00:00.000000",
    "postType": "인사",
    "recommendCnt": 1,
    "viewCnt": 33,
    "uriTitle": "네이버",
    "urlPath": "https://www.naver.com/",
    "tags": "",
    "imageUrls": [],
    "recommended": false
  },
  {
    "postId": 12,
    "nickName": "작성자12",
    "title": "게시글 제목 예시 12",
    "content": "게시글 내용 예시입니다. 12",
    "createdAt": "2025.02.13T00:00:00.000000",
    "postType": "질문",
    "recommendCnt": 2,
    "viewCnt": 36,
    "uriTitle": "구글",
    "urlPath": "https://www.google.com/",
    "tags": "",
    "imageUrls": [],
    "recommended": false
  },
  {
    "postId": 13,
    "nickName": "작성자13",
    "title": "게시글 제목 예시 13",
    "content": "게시글 내용 예시입니다. 13",
    "createdAt": "2025.02.14T00:00:00.000000",
    "postType": "자유",
    "recommendCnt": 3,
    "viewCnt": 39,
    "uriTitle": "네이버",
    "urlPath": "https://www.naver.com/",
    "tags": "",
    "imageUrls": [],
    "recommended": false
  },
  {
    "postId": 14,
    "nickName": "작성자14",
    "title": "게시글 제목 예시 14",
    "content": "게시글 내용 예시입니다. 14",
    "createdAt": "2025.02.15T00:00:00.000000",
    "postType": "인사",
    "recommendCnt": 4,
    "viewCnt": 42,
    "uriTitle": "구글",
    "urlPath": "https://www.google.com/",
    "tags": "",
    "imageUrls": [],
    "recommended": false
  },
  {
    "postId": 15,
    "nickName": "작성자15",
    "title": "게시글 제목 예시 15",
    "content": "게시글 내용 예시입니다. 15",
    "createdAt": "2025.02.16T00:00:00.000000",
    "postType": "질문",
    "recommendCnt": 5,
    "viewCnt": 45,
    "uriTitle": "네이버",
    "urlPath": "https://www.naver.com/",
    "tags": "",
    "imageUrls": [],
    "recommended": false
  },
  {
    "postId": 16,
    "nickName": "작성자16",
    "title": "게시글 제목 예시 16",
    "content": "게시글 내용 예시입니다. 16",
    "createdAt": "2025.02.17T00:00:00.000000",
    "postType": "자유",
    "recommendCnt": 6,
    "viewCnt": 48,
    "uriTitle": "구글",
    "urlPath": "https://www.google.com/",
    "tags": "",
    "imageUrls": [],
    "recommended": false
  },
  {
    "postId": 17,
    "nickName": "작성자17",
    "title": "게시글 제목 예시 17",
    "content": "게시글 내용 예시입니다. 17",
    "createdAt": "2025.02.18T00:00:00.000000",
    "postType": "인사",
    "recommendCnt": 7,
    "viewCnt": 51,
    "uriTitle": "네이버",
    "urlPath": "https://www.naver.com/",
    "tags": "",
    "imageUrls": [],
    "recommended": false
  },
  {
    "postId": 18,
    "nickName": "작성자18",
    "title": "게시글 제목 예시 18",
    "content": "게시글 내용 예시입니다. 18",
    "createdAt": "2025.02.19T00:00:00.000000",
    "postType": "질문",
    "recommendCnt": 8,
    "viewCnt": 54,
    "uriTitle": "구글",
    "urlPath": "https://www.google.com/",
    "tags": "",
    "imageUrls": [],
    "recommended": false
  },
  {
    "postId": 19,
    "nickName": "작성자19",
    "title": "게시글 제목 예시 19",
    "content": "게시글 내용 예시입니다. 19",
    "createdAt": "2025.02.20T00:00:00.000000",
    "postType": "자유",
    "recommendCnt": 9,
    "viewCnt": 57,
    "uriTitle": "네이버",
    "urlPath": "https://www.naver.com/",
    "tags": "",
    "imageUrls": [],
    "recommended": false
  },
  {
    "postId": 20,
    "nickName": "작성자20",
    "title": "게시글 제목 예시 20",
    "content": "게시글 내용 예시입니다. 20",
    "createdAt": "2025.02.21T00:00:00.000000",
    "postType": "인사",
    "recommendCnt": 0,
    "viewCnt": 60,
    "uriTitle": "구글",
    "urlPath": "https://www.google.com/",
    "tags": "",
    "imageUrls": [],
    "recommended": false
  },
  {
    "postId": 21,
    "nickName": "작성자21",
    "title": "게시글 제목 예시 21",
    "content": "게시글 내용 예시입니다. 21",
    "createdAt": "2025.02.22T00:00:00.000000",
    "postType": "질문",
    "recommendCnt": 1,
    "viewCnt": 63,
    "uriTitle": "네이버",
    "urlPath": "https://www.naver.com/",
    "tags": "",
    "imageUrls": [],
    "recommended": false
  },
  {
    "postId": 22,
    "nickName": "작성자22",
    "title": "게시글 제목 예시 22",
    "content": "게시글 내용 예시입니다. 22",
    "createdAt": "2025.02.23T00:00:00.000000",
    "postType": "자유",
    "recommendCnt": 2,
    "viewCnt": 66,
    "uriTitle": "구글",
    "urlPath": "https://www.google.com/",
    "tags": "",
    "imageUrls": [],
    "recommended": false
  },
  {
    "postId": 23,
    "nickName": "작성자23",
    "title": "게시글 제목 예시 23",
    "content": "게시글 내용 예시입니다. 23",
    "createdAt": "2025.02.24T00:00:00.000000",
    "postType": "인사",
    "recommendCnt": 3,
    "viewCnt": 69,
    "uriTitle": "네이버",
    "urlPath": "https://www.naver.com/",
    "tags": "",
    "imageUrls": [],
    "recommended": false
  },
  {
    "postId": 24,
    "nickName": "작성자24",
    "title": "게시글 제목 예시 24",
    "content": "게시글 내용 예시입니다. 24",
    "createdAt": "2025.02.25T00:00:00.000000",
    "postType": "질문",
    "recommendCnt": 4,
    "viewCnt": 72,
    "uriTitle": "구글",
    "urlPath": "https://www.google.com/",
    "tags": "",
    "imageUrls": [],
    "recommended": false
  },
  {
    "postId": 25,
    "nickName": "작성자25",
    "title": "게시글 제목 예시 25",
    "content": "게시글 내용 예시입니다. 25",
    "createdAt": "2025.02.26T00:00:00.000000",
    "postType": "자유",
    "recommendCnt": 5,
    "viewCnt": 75,
    "uriTitle": "네이버",
    "urlPath": "https://www.naver.com/",
    "tags": "",
    "imageUrls": [],
    "recommended": false
  },
  {
    "postId": 26,
    "nickName": "작성자26",
    "title": "게시글 제목 예시 26",
    "content": "게시글 내용 예시입니다. 26",
    "createdAt": "2025.02.27T00:00:00.000000",
    "postType": "인사",
    "recommendCnt": 6,
    "viewCnt": 78,
    "uriTitle": "구글",
    "urlPath": "https://www.google.com/",
    "tags": "",
    "imageUrls": [],
    "recommended": false
  },
  {
    "postId": 27,
    "nickName": "작성자27",
    "title": "게시글 제목 예시 27",
    "content": "게시글 내용 예시입니다. 27",
    "createdAt": "2025.02.28T00:00:00.000000",
    "postType": "질문",
    "recommendCnt": 7,
    "viewCnt": 81,
    "uriTitle": "네이버",
    "urlPath": "https://www.naver.com/",
    "tags": "",
    "imageUrls": [],
    "recommended": false
  },
  {
    "postId": 28,
    "nickName": "작성자28",
    "title": "게시글 제목 예시 28",
    "content": "게시글 내용 예시입니다. 28",
    "createdAt": "2025.02.01T00:00:00.000000",
    "postType": "자유",
    "recommendCnt": 8,
    "viewCnt": 84,
    "uriTitle": "구글",
    "urlPath": "https://www.google.com/",
    "tags": "",
    "imageUrls": [],
    "recommended": false
  },
  {
    "postId": 29,
    "nickName": "작성자29",
    "title": "게시글 제목 예시 29",
    "content": "게시글 내용 예시입니다. 29",
    "createdAt": "2025.02.02T00:00:00.000000",
    "postType": "인사",
    "recommendCnt": 9,
    "viewCnt": 87,
    "uriTitle": "네이버",
    "urlPath": "https://www.naver.com/",
    "tags": "",
    "imageUrls": [],
    "recommended": false
  },
  {
    "postId": 30,
    "nickName": "작성자30",
    "title": "게시글 제목 예시 30",
    "content": "게시글 내용 예시입니다. 30",
    "createdAt": "2025.02.03T00:00:00.000000",
    "postType": "질문",
    "recommendCnt": 0,
    "viewCnt": 90,
    "uriTitle": "구글",
    "urlPath": "https://www.google.com/",
    "tags": "",
    "imageUrls": [],
    "recommended": false
  }
];