export const dummyBoardList = [
    {
      id: 31,
      title: '이제 성인이 되는 사람인데 추천할만 혜택있나요?',
      author: '채택이',
      date: '2025.02.17',
      views: 5,
      type: '질문',
    },
    {
      id: 30,
      title: '대학생 무료 프로그램 뭐가 있을까요?',
      author: '혜택알리미',
      date: '2025.02.15',
      views: 12,
      type: '질문',
    },
    {
      id: 29,
      title: '오늘 점심 추천해주세요!',
      author: '맛잘알',
      date: '2025.02.14', 
      views: 8,
      type: '자유',
    },
    {
      id: 28,
      title: '처음 가입했어요! 반갑습니다!',
      author: '신입회원',
      date: '2025.02.13',
      views: 20,
      type: '인사',
    },
    {
      id: 27,
      title: '정부 청년 지원금 총정리',
      author: '알뜰정보',
      date: '2025.02.12',
      views: 45,
      type: '질문',
    },
    {
      id: 26,
      title: '토익 공부 어떻게 시작하시나요?',
      author: '스터디중',
      date: '2025.02.11',
      views: 18,
      type: '질문',
    },
    {
      id: 25,
      title: '운동 루틴 공유합니다',
      author: '헬창',
      date: '2025.02.10',
      views: 30,
      type: '자유',
    },
    {
      id: 24,
      title: '첫 글 남깁니다. 다들 안녕하세요!',
      author: '반가워요',
      date: '2025.02.09',
      views: 15,
      type: '인사',
    },
    {
      id: 23,
      title: '2025년 복지 혜택 요약',
      author: '정보왕',
      date: '2025.02.08',
      views: 55,
      type: '질문',
    },
    {
      id: 22,
      title: '다이어트 식단 추천 부탁드려요',
      author: '다이어터',
      date: '2025.02.07',
      views: 22,
      type: '자유',
    },
    {
        id: 21,
        title: '이제 성인이 되는 사람인데 추천할만 혜택있나요?',
        author: '채택이',
        date: '2025.02.17',
        views: 5,
        type: '질문',
      },
      {
        id: 20,
        title: '대학생 무료 프로그램 뭐가 있을까요?',
        author: '혜택알리미',
        date: '2025.02.15',
        views: 12,
        type: '질문',
      },
      {
        id: 19,
        title: '오늘 점심 추천해주세요!',
        author: '맛잘알',
        date: '2025.02.14',
        views: 8,
        type: '자유',
      },
      {
        id: 18,
        title: '처음 가입했어요! 반갑습니다!',
        author: '신입회원',
        date: '2025.02.13',
        views: 20,
        type: '인사',
      },
      {
        id: 17,
        title: '정부 청년 지원금 총정리',
        author: '알뜰정보',
        date: '2025.02.12',
        views: 45,
        type: '질문',
      },
      {
        id: 16,
        title: '토익 공부 어떻게 시작하시나요?',
        author: '스터디중',
        date: '2025.02.11',
        views: 18,
        type: '질문',
      },
      {
        id: 15,
        title: '운동 루틴 공유합니다',
        author: '헬창',
        date: '2025.02.10',
        views: 30,
        type: '자유',
      },
      {
        id: 14,
        title: '첫 글 남깁니다. 다들 안녕하세요!',
        author: '반가워요',
        date: '2025.02.09',
        views: 15,
        type: '인사',
      },
      {
        id: 13,
        title: '2025년 복지 혜택 요약',
        author: '정보왕',
        date: '2025.02.08',
        views: 55,
        type: '질문',
      },
      {
        id: 12,
        title: '다이어트 식단 추천 부탁드려요',
        author: '다이어터',
        date: '2025.02.07',
        views: 22,
        type: '자유',
      },
      {
        id: 11,
        title: '다이어트 식단 추천 부탁드려요',
        author: '다이어터',
        date: '2025.02.07',
        views: 22,
        type: '자유',
      },
      {
        id: 10,
        title: '다이어트 식단 추천 부탁드려요',
        author: '다이어터',
        date: '2025.02.07',
        views: 22,
        type: '자유',
      },
      {
        id: 9,
        title: '다이어트 식단 추천 부탁드려요',
        author: '다이어터',
        date: '2025.02.07',
        views: 22,
        type: '자유',
      },
      {
        id: 8,
        title: '다이어트 식단 추천 부탁드려요',
        author: '다이어터',
        date: '2025.02.07',
        views: 22,
        type: '자유',
      },
      {
        id: 7,
        title: '다이어트 식단 추천 부탁드려요',
        author: '다이어터',
        date: '2025.02.07',
        views: 22,
        type: '자유',
      },
      {
        id: 6,
        title: '다이어트 식단 추천 부탁드려요',
        author: '다이어터',
        date: '2025.02.07',
        views: 22,
        type: '자유',
      },
      {
        id: 5,
        title: '다이어트 식단 추천 부탁드려요',
        author: '다이어터',
        date: '2025.02.07',
        views: 22,
        type: '자유',
      },
      {
        id: 4,
        title: '다이어트 식단 추천 부탁드려요',
        author: '다이어터',
        date: '2025.02.07',
        views: 22,
        type: '자유',
      },
      {
        id: 3,
        title: '다이어트 식단 추천 부탁드려요',
        author: '다이어터',
        date: '2025.02.07',
        views: 22,
        type: '자유',
      },
      {
        id: 2,
        title: '다이어트 식단 추천 부탁드려요',
        author: '다이어터',
        date: '2025.02.07',
        views: 22,
        type: '자유',
      },
      {
        id: 1,
        title: '다이어트 식단 추천 부탁드려요',
        author: '다이어터',
        date: '2025.02.07',
        views: 22,
        type: '자유',
      },

  ];
  